# Generated by Django 4.1.1 on 2022-09-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('ID', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=80)),
                ('Abstract', models.TextField(max_length=800)),
                ('GeneralCategory', models.CharField(max_length=20)),
                ('Category', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Journal',
            },
        ),
    ]
