# Generated by Django 4.1.1 on 2022-09-18 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0002_journalrecommendationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='ID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
